language: ruby
os: linux
sudo: false

# Test with supported td-agent versions
# https://docs.fluentd.org/quickstart/support#change-logs
# https://docs.treasuredata.com/display/public/PD/The+td-agent+Change+Log
# https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/CHANGELOG.md
matrix:
  include:
    - gemfile: gemfiles/Gemfile.fluentd-1.12.3 # Latest Fluentd / https://www.fluentd.org/download
      rvm: 2.7.3 # Latest supported Ruby (less than v3.0.0) / https://www.ruby-lang.org/en/downloads
    - gemfile: gemfiles/Gemfile.fluentd-0.14.22 # Oldest supported Fluentd
      rvm: 2.3.0 # Oldest supported Ruby
    - gemfile: gemfiles/Gemfile.td-agent-3.1.0
      rvm: 2.4.2 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.1.0/config/projects/td-agent3.rb#L20
    # - gemfile: gemfiles/Gemfile.td-agent-3.1.1
    #   rvm: 2.4.2 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.1.1/config/projects/td-agent3.rb#L17
    # - gemfile: gemfiles/Gemfile.td-agent-3.2.0
    #   rvm: 2.4.4 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.2.0/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.2.1
      rvm: 2.4.4 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.2.1/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.3.0
      rvm: 2.4.5 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.3.0/config/projects/td-agent3.rb#L22
    # - gemfile: gemfiles/Gemfile.td-agent-3.4.0
    #   rvm: 2.4.5 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.4.0/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.4.1
      rvm: 2.4.6 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.4.1/config/projects/td-agent3.rb#L22
    # - gemfile: gemfiles/Gemfile.td-agent-3.5.0
    #   rvm: 2.4.6 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.5.0/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.5.1
      rvm: 2.4.9 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.5.1/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.6.0
      rvm: 2.4.9 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.6.0/config/projects/td-agent3.rb#L22
    # - gemfile: gemfiles/Gemfile.td-agent-3.7.0
    #   rvm: 2.4.9 # https://github.com/treasure-data/omnibus-td-agent/commit/da5cb39ec5396f652cd30bad5bb8ef4ec19071a9#diff-f73e763ace61e7c4bf48bf94bd6e295bc2cfd1ce5f9e38a4d19e266353e37498R22
    - gemfile: gemfiles/Gemfile.td-agent-3.7.1
      rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.7.1/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.8.0 # Latest official release of td-agent v3
      rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.8.0/config/projects/td-agent3.rb#L22
    - gemfile: gemfiles/Gemfile.td-agent-3.8.1 # Maintenance release of td-agent v3
      rvm: 2.4.10 # https://github.com/treasure-data/omnibus-td-agent/pull/273/files#diff-f73e763ace61e7c4bf48bf94bd6e295bc2cfd1ce5f9e38a4d19e266353e37498R22
    # - gemfile: gemfiles/Gemfile.td-agent-4.0.0
    #   rvm: 2.7.1 # https://github.com/fluent-plugins-nursery/td-agent-builder/blob/41b3436d43c21e48a9cf34c58ae640f0e3dfb44c/td-agent/config.rb#L16
    - gemfile: gemfiles/Gemfile.td-agent-4.0.1
      rvm: 2.7.1 # https://github.com/fluent-plugins-nursery/td-agent-builder/blob/v4.0.1/td-agent/config.rb#L16
    - gemfile: gemfiles/Gemfile.td-agent-4.1.0
      rvm: 2.7.2 # https://github.com/fluent-plugins-nursery/td-agent-builder/blob/v4.1.0/td-agent/config.rb#L19
  fast_finish: true

script: bundle exec rake test
